services:
  - type: web
    name: spendbetter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "run:app" --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /tmp/app.db
      - key: FLASK_ENV
        value: production
    plan: free
